package mariadb

import "core:c"

// ─── Field Type Flags ───────────────────────────────────────────────────────

NOT_NULL_FLAG :: 1
PRI_KEY_FLAG :: 2
UNIQUE_KEY_FLAG :: 4
MULTIPLE_KEY_FLAG :: 8
BLOB_FLAG :: 16
UNSIGNED_FLAG :: 32
ZEROFILL_FLAG :: 64
BINARY_FLAG :: 128
ENUM_FLAG :: 256
AUTO_INCREMENT_FLAG :: 512
TIMESTAMP_FLAG :: 1024
SET_FLAG :: 2048
NO_DEFAULT_VALUE_FLAG :: 4096
ON_UPDATE_NOW_FLAG :: 8192
PART_KEY_FLAG :: 16384
GROUP_FLAG :: 32768
NUM_FLAG :: 32768
UNIQUE_FLAG :: 65536

// ─── Refresh Options ────────────────────────────────────────────────────────

REFRESH_GRANT :: 1
REFRESH_LOG :: 2
REFRESH_TABLES :: 4
REFRESH_HOSTS :: 8
REFRESH_STATUS :: 16
REFRESH_THREADS :: 32
REFRESH_SLAVE :: 64
REFRESH_MASTER :: 128
REFRESH_READ_LOCK :: 16384
REFRESH_FAST :: 32768

// ─── Client Flags ───────────────────────────────────────────────────────────

CLIENT_MYSQL :: 1
CLIENT_FOUND_ROWS :: 2
CLIENT_LONG_FLAG :: 4
CLIENT_CONNECT_WITH_DB :: 8
CLIENT_NO_SCHEMA :: 16
CLIENT_COMPRESS :: 32
CLIENT_ODBC :: 64
CLIENT_LOCAL_FILES :: 128
CLIENT_IGNORE_SPACE :: 256
CLIENT_INTERACTIVE :: 1024
CLIENT_SSL :: 2048
CLIENT_IGNORE_SIGPIPE :: 4096
CLIENT_TRANSACTIONS :: 8192
CLIENT_PROTOCOL_41 :: 512
CLIENT_RESERVED :: 16384
CLIENT_SECURE_CONNECTION :: 32768
CLIENT_MULTI_STATEMENTS :: (1 << 16)
CLIENT_MULTI_RESULTS :: (1 << 17)
CLIENT_PS_MULTI_RESULTS :: (1 << 18)
CLIENT_PLUGIN_AUTH :: (1 << 19)
CLIENT_CONNECT_ATTRS :: (1 << 20)
CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA :: (1 << 21)
CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS :: (1 << 22)
CLIENT_SESSION_TRACKING :: (1 << 23)
CLIENT_ZSTD_COMPRESSION :: (1 << 26)
CLIENT_PROGRESS :: (1 << 29)
CLIENT_SSL_VERIFY_SERVER_CERT :: (1 << 30)
CLIENT_REMEMBER_OPTIONS :: (1 << 31)

// MariaDB-specific client capabilities
MARIADB_CLIENT_PROGRESS :: (1 << 32)
MARIADB_CLIENT_STMT_BULK_OPERATIONS :: (1 << 34)
MARIADB_CLIENT_EXTENDED_METADATA :: (1 << 35)
MARIADB_CLIENT_CACHE_METADATA :: (1 << 36)
MARIADB_CLIENT_BULK_UNIT_RESULTS :: (1 << 37)

// ─── Server Status ──────────────────────────────────────────────────────────

SERVER_STATUS_IN_TRANS :: 1
SERVER_STATUS_AUTOCOMMIT :: 2
SERVER_MORE_RESULTS_EXIST :: 8
SERVER_QUERY_NO_GOOD_INDEX_USED :: 16
SERVER_QUERY_NO_INDEX_USED :: 32
SERVER_STATUS_CURSOR_EXISTS :: 64
SERVER_STATUS_LAST_ROW_SENT :: 128
SERVER_STATUS_DB_DROPPED :: 256
SERVER_STATUS_NO_BACKSLASH_ESCAPES :: 512
SERVER_STATUS_METADATA_CHANGED :: 1024
SERVER_QUERY_WAS_SLOW :: 2048
SERVER_PS_OUT_PARAMS :: 4096
SERVER_STATUS_IN_TRANS_READONLY :: 8192
SERVER_SESSION_STATE_CHANGED :: 16384
SERVER_STATUS_ANSI_QUOTES :: 32768

// ─── Connection Types ───────────────────────────────────────────────────────

MARIADB_CONNECTION_UNIXSOCKET :: 0
MARIADB_CONNECTION_TCP :: 1
MARIADB_CONNECTION_NAMEDPIPE :: 2
MARIADB_CONNECTION_SHAREDMEM :: 3

// ─── Misc Constants ─────────────────────────────────────────────────────────

MYSQL_ERRMSG_SIZE :: 512
SQLSTATE_LENGTH :: 5
SCRAMBLE_LENGTH :: 20
NAME_CHAR_LEN :: 64
NAME_LEN :: 256
HOSTNAME_LENGTH :: 255
USERNAME_CHAR_LENGTH :: 128
SERVER_VERSION_LENGTH :: 60
LOCAL_INFILE_ERROR_LEN :: 512
MYSQL_COUNT_ERROR :: ~c.ulonglong(0)

MYSQL_WAIT_READ :: 1
MYSQL_WAIT_WRITE :: 2
MYSQL_WAIT_EXCEPT :: 4
MYSQL_WAIT_TIMEOUT :: 8

MARIADB_INVALID_SOCKET :: -1

NULL_LENGTH :: ~c.ulong(0)

// ─── MARIADB_TLS_VERIFY_* ───────────────────────────────────────────────────

MARIADB_TLS_VERIFY_OK :: 0
MARIADB_TLS_VERIFY_TRUST :: 1
MARIADB_TLS_VERIFY_HOST :: 2
MARIADB_TLS_VERIFY_FINGERPRINT :: 4
MARIADB_TLS_VERIFY_PERIOD :: 8
MARIADB_TLS_VERIFY_REVOKED :: 16
MARIADB_TLS_VERIFY_UNKNOWN :: 32
MARIADB_TLS_VERIFY_ERROR :: 128

// ─── enum_item_result ───────────────────────────────────────────────────────

Item_result :: enum c.int {
	STRING_RESULT,
	REAL_RESULT,
	INT_RESULT,
	ROW_RESULT,
	DECIMAL_RESULT,
}

// ─── mysql_enum_shutdown_level ──────────────────────────────────────────────

mysql_enum_shutdown_level :: enum c.int {
	SHUTDOWN_DEFAULT = 0,
	KILL_QUERY       = 254,
	KILL_CONNECTION  = 255,
}

// ─── enum_server_command ────────────────────────────────────────────────────

enum_server_command :: enum c.int {
	COM_SLEEP,
	COM_QUIT,
	COM_INIT_DB,
	COM_QUERY,
	COM_FIELD_LIST,
	COM_CREATE_DB,
	COM_DROP_DB,
	COM_REFRESH,
	COM_SHUTDOWN,
	COM_STATISTICS,
	COM_PROCESS_INFO,
	COM_CONNECT,
	COM_PROCESS_KILL,
	COM_DEBUG,
	COM_PING,
	COM_TIME                        = 15,
	COM_DELAYED_INSERT,
	COM_CHANGE_USER,
	COM_BINLOG_DUMP,
	COM_TABLE_DUMP,
	COM_CONNECT_OUT                 = 20,
	COM_REGISTER_SLAVE,
	COM_STMT_PREPARE                = 22,
	COM_STMT_EXECUTE                = 23,
	COM_STMT_SEND_LONG_DATA         = 24,
	COM_STMT_CLOSE                  = 25,
	COM_STMT_RESET                  = 26,
	COM_SET_OPTION                  = 27,
	COM_STMT_FETCH                  = 28,
	COM_DAEMON                      = 29,
	COM_UNSUPPORTED                 = 30,
	COM_RESET_CONNECTION            = 31,
	COM_STMT_BULK_EXECUTE           = 250,
	COM_RESERVED_1                  = 254,
	COM_END,
}

// ─── enum_field_types ───────────────────────────────────────────────────────

enum_field_types :: enum c.int {
	MYSQL_TYPE_DECIMAL,
	MYSQL_TYPE_TINY,
	MYSQL_TYPE_SHORT,
	MYSQL_TYPE_LONG,
	MYSQL_TYPE_FLOAT,
	MYSQL_TYPE_DOUBLE,
	MYSQL_TYPE_NULL,
	MYSQL_TYPE_TIMESTAMP,
	MYSQL_TYPE_LONGLONG,
	MYSQL_TYPE_INT24,
	MYSQL_TYPE_DATE,
	MYSQL_TYPE_TIME,
	MYSQL_TYPE_DATETIME,
	MYSQL_TYPE_YEAR,
	MYSQL_TYPE_NEWDATE,
	MYSQL_TYPE_VARCHAR,
	MYSQL_TYPE_BIT,
	MYSQL_TYPE_TIMESTAMP2,
	MYSQL_TYPE_DATETIME2,
	MYSQL_TYPE_TIME2,
	MYSQL_TYPE_JSON        = 245,
	MYSQL_TYPE_NEWDECIMAL  = 246,
	MYSQL_TYPE_ENUM        = 247,
	MYSQL_TYPE_SET         = 248,
	MYSQL_TYPE_TINY_BLOB   = 249,
	MYSQL_TYPE_MEDIUM_BLOB = 250,
	MYSQL_TYPE_LONG_BLOB   = 251,
	MYSQL_TYPE_BLOB        = 252,
	MYSQL_TYPE_VAR_STRING  = 253,
	MYSQL_TYPE_STRING      = 254,
	MYSQL_TYPE_GEOMETRY    = 255,
	MAX_NO_FIELD_TYPES,
}

// ─── enum_mysql_timestamp_type ──────────────────────────────────────────────

enum_mysql_timestamp_type :: enum c.int {
	MYSQL_TIMESTAMP_NONE     = -2,
	MYSQL_TIMESTAMP_ERROR    = -1,
	MYSQL_TIMESTAMP_DATE     = 0,
	MYSQL_TIMESTAMP_DATETIME = 1,
	MYSQL_TIMESTAMP_TIME     = 2,
}

// ─── enum_mysql_set_option ──────────────────────────────────────────────────

enum_mysql_set_option :: enum c.int {
	MYSQL_OPTION_MULTI_STATEMENTS_ON,
	MYSQL_OPTION_MULTI_STATEMENTS_OFF,
}

// ─── mysql_option ───────────────────────────────────────────────────────────

mysql_option :: enum c.int {
	MYSQL_OPT_CONNECT_TIMEOUT,
	MYSQL_OPT_COMPRESS,
	MYSQL_OPT_NAMED_PIPE,
	MYSQL_INIT_COMMAND,
	MYSQL_READ_DEFAULT_FILE,
	MYSQL_READ_DEFAULT_GROUP,
	MYSQL_SET_CHARSET_DIR,
	MYSQL_SET_CHARSET_NAME,
	MYSQL_OPT_LOCAL_INFILE,
	MYSQL_OPT_PROTOCOL,
	MYSQL_SHARED_MEMORY_BASE_NAME,
	MYSQL_OPT_READ_TIMEOUT,
	MYSQL_OPT_WRITE_TIMEOUT,
	MYSQL_OPT_USE_RESULT,
	MYSQL_OPT_USE_REMOTE_CONNECTION,
	MYSQL_OPT_USE_EMBEDDED_CONNECTION,
	MYSQL_OPT_GUESS_CONNECTION,
	MYSQL_SET_CLIENT_IP,
	MYSQL_SECURE_AUTH,
	MYSQL_REPORT_DATA_TRUNCATION,
	MYSQL_OPT_RECONNECT,
	MYSQL_OPT_SSL_VERIFY_SERVER_CERT,
	MYSQL_PLUGIN_DIR,
	MYSQL_DEFAULT_AUTH,
	MYSQL_OPT_BIND,
	MYSQL_OPT_SSL_KEY,
	MYSQL_OPT_SSL_CERT,
	MYSQL_OPT_SSL_CA,
	MYSQL_OPT_SSL_CAPATH,
	MYSQL_OPT_SSL_CIPHER,
	MYSQL_OPT_SSL_CRL,
	MYSQL_OPT_SSL_CRLPATH,
	MYSQL_OPT_CONNECT_ATTR_RESET,
	MYSQL_OPT_CONNECT_ATTR_ADD,
	MYSQL_OPT_CONNECT_ATTR_DELETE,
	MYSQL_SERVER_PUBLIC_KEY,
	MYSQL_ENABLE_CLEARTEXT_PLUGIN,
	MYSQL_OPT_CAN_HANDLE_EXPIRED_PASSWORDS,
	MYSQL_OPT_SSL_ENFORCE,
	MYSQL_OPT_MAX_ALLOWED_PACKET,
	MYSQL_OPT_NET_BUFFER_LENGTH,
	MYSQL_OPT_TLS_VERSION,
	MYSQL_OPT_ZSTD_COMPRESSION_LEVEL,
	// MariaDB-specific
	MYSQL_PROGRESS_CALLBACK            = 5999,
	MYSQL_OPT_NONBLOCK,
	// MariaDB Connector/C specific
	MYSQL_DATABASE_DRIVER              = 7000,
	MARIADB_OPT_SSL_FP,                // deprecated
	MARIADB_OPT_SSL_FP_LIST,           // deprecated
	MARIADB_OPT_TLS_PASSPHRASE,
	MARIADB_OPT_TLS_CIPHER_STRENGTH,
	MARIADB_OPT_TLS_VERSION,
	MARIADB_OPT_TLS_PEER_FP,
	MARIADB_OPT_TLS_PEER_FP_LIST,
	MARIADB_OPT_CONNECTION_READ_ONLY,
	MYSQL_OPT_CONNECT_ATTRS,
	MARIADB_OPT_USERDATA,
	MARIADB_OPT_CONNECTION_HANDLER,
	MARIADB_OPT_PORT,
	MARIADB_OPT_UNIXSOCKET,
	MARIADB_OPT_PASSWORD,
	MARIADB_OPT_HOST,
	MARIADB_OPT_USER,
	MARIADB_OPT_SCHEMA,
	MARIADB_OPT_DEBUG,
	MARIADB_OPT_FOUND_ROWS,
	MARIADB_OPT_MULTI_RESULTS,
	MARIADB_OPT_MULTI_STATEMENTS,
	MARIADB_OPT_INTERACTIVE,
	MARIADB_OPT_PROXY_HEADER,
	MARIADB_OPT_IO_WAIT,
	MARIADB_OPT_SKIP_READ_RESPONSE,
	MARIADB_OPT_RESTRICTED_AUTH,
	MARIADB_OPT_RPL_REGISTER_REPLICA,
	MARIADB_OPT_STATUS_CALLBACK,
	MARIADB_OPT_SERVER_PLUGINS,
	MARIADB_OPT_BULK_UNIT_RESULTS,
	MARIADB_OPT_TLS_VERIFICATION_CALLBACK,
}

// ─── mariadb_value ──────────────────────────────────────────────────────────

mariadb_value :: enum c.int {
	MARIADB_CHARSET_ID,
	MARIADB_CHARSET_NAME,
	MARIADB_CLIENT_ERRORS,
	MARIADB_CLIENT_VERSION,
	MARIADB_CLIENT_VERSION_ID,
	MARIADB_CONNECTION_ASYNC_TIMEOUT,
	MARIADB_CONNECTION_ASYNC_TIMEOUT_MS,
	MARIADB_CONNECTION_MARIADB_CHARSET_INFO,
	MARIADB_CONNECTION_ERROR,
	MARIADB_CONNECTION_ERROR_ID,
	MARIADB_CONNECTION_HOST,
	MARIADB_CONNECTION_INFO,
	MARIADB_CONNECTION_PORT,
	MARIADB_CONNECTION_PROTOCOL_VERSION_ID,
	MARIADB_CONNECTION_PVIO_TYPE,
	MARIADB_CONNECTION_SCHEMA,
	MARIADB_CONNECTION_SERVER_TYPE,
	MARIADB_CONNECTION_SERVER_VERSION,
	MARIADB_CONNECTION_SERVER_VERSION_ID,
	MARIADB_CONNECTION_SOCKET,
	MARIADB_CONNECTION_SQLSTATE,
	MARIADB_CONNECTION_SSL_CIPHER,
	MARIADB_TLS_LIBRARY,
	MARIADB_CONNECTION_TLS_VERSION,
	MARIADB_CONNECTION_TLS_VERSION_ID,
	MARIADB_CONNECTION_TYPE,
	MARIADB_CONNECTION_UNIX_SOCKET,
	MARIADB_CONNECTION_USER,
	MARIADB_MAX_ALLOWED_PACKET,
	MARIADB_NET_BUFFER_LENGTH,
	MARIADB_CONNECTION_SERVER_STATUS,
	MARIADB_CONNECTION_SERVER_CAPABILITIES,
	MARIADB_CONNECTION_EXTENDED_SERVER_CAPABILITIES,
	MARIADB_CONNECTION_CLIENT_CAPABILITIES,
	MARIADB_CONNECTION_BYTES_READ,
	MARIADB_CONNECTION_BYTES_SENT,
	MARIADB_TLS_PEER_CERT_INFO,
	MARIADB_TLS_VERIFY_STATUS,
}

// ─── mysql_status ───────────────────────────────────────────────────────────

mysql_status :: enum c.int {
	MYSQL_STATUS_READY,
	MYSQL_STATUS_GET_RESULT,
	MYSQL_STATUS_USE_RESULT,
	MYSQL_STATUS_QUERY_SENT,
	MYSQL_STATUS_SENDING_LOAD_DATA,
	MYSQL_STATUS_FETCHING_DATA,
	MYSQL_STATUS_NEXT_RESULT_PENDING,
	MYSQL_STATUS_QUIT_SENT,
	MYSQL_STATUS_STMT_RESULT,
}

// ─── mysql_protocol_type ────────────────────────────────────────────────────

mysql_protocol_type :: enum c.int {
	MYSQL_PROTOCOL_DEFAULT,
	MYSQL_PROTOCOL_TCP,
	MYSQL_PROTOCOL_SOCKET,
	MYSQL_PROTOCOL_PIPE,
	MYSQL_PROTOCOL_MEMORY,
}

// ─── mariadb_field_attr_t ───────────────────────────────────────────────────

mariadb_field_attr_t :: enum c.int {
	MARIADB_FIELD_ATTR_DATA_TYPE_NAME = 0,
	MARIADB_FIELD_ATTR_FORMAT_NAME    = 1,
}

MARIADB_FIELD_ATTR_LAST :: mariadb_field_attr_t.MARIADB_FIELD_ATTR_FORMAT_NAME

// ─── enum_mariadb_status_info ───────────────────────────────────────────────

enum_mariadb_status_info :: enum c.int {
	STATUS_TYPE      = 0,
	SESSION_TRACK_TYPE,
}

// ─── enum_session_state_type ────────────────────────────────────────────────

enum_session_state_type :: enum c.int {
	SESSION_TRACK_SYSTEM_VARIABLES         = 0,
	SESSION_TRACK_SCHEMA,
	SESSION_TRACK_STATE_CHANGE,
	SESSION_TRACK_GTIDS,
	SESSION_TRACK_TRANSACTION_CHARACTERISTICS,
	SESSION_TRACK_TRANSACTION_STATE,
}

// ─── mariadb_tls_verification ───────────────────────────────────────────────

mariadb_tls_verification :: enum c.int {
	MARIADB_VERIFY_NONE       = 0,
	MARIADB_VERIFY_PIPE,
	MARIADB_VERIFY_UNIXSOCKET,
	MARIADB_VERIFY_LOCALHOST,
	MARIADB_VERIFY_FINGERPRINT,
	MARIADB_VERIFY_PEER_CERT,
}

// ─── enum_pvio_timeout ──────────────────────────────────────────────────────

enum_pvio_timeout :: enum c.int {
	PVIO_CONNECT_TIMEOUT = 0,
	PVIO_READ_TIMEOUT,
	PVIO_WRITE_TIMEOUT,
}

// ─── enum_pvio_type ─────────────────────────────────────────────────────────

enum_pvio_type :: enum c.int {
	PVIO_TYPE_UNIXSOCKET = 0,
	PVIO_TYPE_SOCKET,
	PVIO_TYPE_NAMEDPIPE,
	PVIO_TYPE_SHAREDMEM,
}

// ─── enum_pvio_tls_type ─────────────────────────────────────────────────────

enum_pvio_tls_type :: enum c.int {
	SSL_TYPE_DEFAULT = 0,
	SSL_TYPE_OPENSSL,
	SSL_TYPE_GNUTLS,
}

// ─── TLS Protocol Constants ─────────────────────────────────────────────────

PROTOCOL_SSLV3   :: 0
PROTOCOL_TLS_1_0 :: 1
PROTOCOL_TLS_1_1 :: 2
PROTOCOL_TLS_1_2 :: 3
PROTOCOL_TLS_1_3 :: 4
PROTOCOL_UNKNOWN :: 5
TLS_VERSION_LENGTH :: 64
